### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by bende01** [june9666/szoftarch-hf-spotifyPlaylistHelper#3]
Szóval a friend hozzáadásnál át kéne állítani, hogy ne user nevet kérjen, hanem a mergelni kívánt playlist id-ját, mert sajna az mindenképpen kell és nincs más egyedi azonosító, ami alapján be lehetne szerezni. Ha teszteled a saját spotify-odban, ha rámész egy lejátszási listára, a Megosztás/Url másolás és hamar be tudod ide illeszteni, csak ki kell törölni ami nem kell, hogy csak az id maradjon (playlist/EZARÉSZ ? a kérdőjel már nem)

**Comment by june9666** [comment]
MoM: user azonosítot egyszer kell megadni, erre jó lesz a jelenlegi mező
