### ISSUE TITLE
PlayList View

### ISSUE THREAD

**Issue by bende01** [june9666/szoftarch-hf-spotifyPlaylistHelper#4]
A számok az, hogy hányszor fordul elő, mivel nem volt más rublika inkább ezt írtam ki az előadó helyett, de ha adsz még nekem rublikát bekötöm azt is. A nagyobb probléma, hogy a create palylist-nek kéne valami értelmes gomb, mert jelenleg a toolbar settings gombjával lehet létrehozni a listát. Ezt megjöltem kódban melyik függvények kellenek, lehetőleg maradj az activity-ben.

**Comment by june9666** [comment]
- playlistview artist mező add
- playlistview floatingaction button add (save)

**Comment by june9666** [comment]
playlistview --> PlaylistItemMatches-be lehet majd írni hogy hany db a közös user
amit, playlistItem --> matches: be lehet tarolni
R.id.fabSave, viszont a playlistview fragmentben van megirva, igy aktivitibol csak akkor hivhato ha mar el a playlistview fragment
playlistview hosszú karakteres számok neveit levágni mert elcsúszik az egész / wont fix
